### ISSUE TITLE
Home screen : show reaction title

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eln-couch#15]
Problem may raised if you change the reaction title (at the level of the reaction) how could the Home screen be aware of this.
Same is true with last modification date that is shown on the Home screen?

**Comment by stropitek** [comment]
The home tab reaction table has a refresh button.

If you want it to be automatic, we either have to poll or to have inter-tab communication

**Comment by stropitek** [comment]
BTW, what do you mean by title? the code of the reaction or the description? Because the code cannot be changed once it's created...

**Comment by lpatiny** [comment]
What appears as "title" in the reaction json
![image](https://cloud.githubusercontent.com/assets/1484241/13183963/a7e61d84-d739-11e5-92f1-09c3037d6650.png)

**Comment by lpatiny** [comment]
OK let's keep the refresh button for the moment.
